[package]
name = "aerostream"
version = "0.1.0"
edition = "2021"
authors = ["AeroStream Team"]
description = "Ultra-low-latency Game Streaming and Remote Desktop Engine in Rust"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
axum = { version = "0.8", features = ["ws"] }
tower-http = { version = "0.6", features = ["cors", "fs"] }
xcap = "0.9"
enigo = "0.6"
image = { version = "0.25", default-features = false, features = ["jpeg"] }
qrcode = "0.14"
local-ip-address = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1.10"
futures-util = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8"
windows-sys = { version = "0.61.2", features = ["Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_Foundation", "Win32_System_StationsAndDesktops", "Win32_System_Threading", "Win32_Security", "Win32_UI_Shell", "Win32_System_Memory", "Win32_System_DataExchange", "Win32_System_LibraryLoader"] }
jpeg-encoder = { version = "0.6", features = ["simd"] }
openh264 = "0.6"
dxgi-capture-rs = "1.2"
fast_image_resize = "6.1.0"
axum-server = { version = "0.7", features = ["tls-rustls"] }
rcgen = "0.13"
rustls = { version = "0.23", default-features = false, features = ["ring"] }
audiopus = "0.2"
cpal = "0.15"
webrtc = "0.17.2"
windows = { version = "0.58", features = [
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
    "Win32_Foundation",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
] }
